### PR TITLE
Handle unicode characters in filters

### LINKED ISSUE #564: Special Characters Not Handled Correctly in Filters
It appears that special characters are not handled correctly in Filters. For example, changing the name to "Bílbo Bággins" by adding accents here causes the test to fail: 

https://github.com/apache/directory-scimple/blob/develop/scim-spec/scim-spec-schema/src/test/java/org/apache/directory/scim/spec/filter/FilterBuilderTest.java#L33-L40

```
line 1:18 token recognition error at: '"Bí'
line 1:21 extraneous input 'lbo' expecting CompValue

org.apache.directory.scim.spec.filter.FilterParseException: Failed to parse filter: name.givenName EQ "Bílbo" AND name.familyName EQ "Bággins"

	at org.apache.directory.scim.spec.filter.Filter.parseFilter(Filter.java:92)
	at org.apache.directory.scim.spec.filter.Filter.setFilter(Filter.java:70)
	at org.apache.directory.scim.spec.filter.Filter.<init>(Filter.java:55)
	at org.apache.directory.scim.spec.filter.FilterBuilderTest.testSimpleAnd(FilterBuilderTest.java:39)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalStateException: failed to parse at line 1:21 due to extraneous input 'lbo' expecting CompValue
	at org.apache.directory.scim.spec.filter.Filter$1.syntaxError(Filter.java:81)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
	at org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:467)
	at org.antlr.v4.runtime.Parser.match(Parser.java:208)
	at org.apache.directory.scim.spec.filter.FilterParser.filterExpression(FilterParser.java:459)
	at org.apache.directory.scim.spec.filter.FilterParser.filter(FilterParser.java:128)
	at org.apache.directory.scim.spec.filter.Filter.parseFilter(Filter.java:86)
	... 6 more
```

### PR DESCRIPTION
**Pull request by bdemers**
- Updated ANTLR4 grammar to support unicode chars
- Added test
- Removed logic that escapes/unescapes JSON values, should is handled by at the JSON parser (jackson)

Fixes: #564

### CODE REVIEW

**Comment by bdemers** [comment]
@joshuapsteele, took a little longer to track the issue down, but when you get a chance can you take a look at this.

@chrisharm if you are still watching can you take a look at this too? I'm guessing this logic was here for a reason and I'm guessing I shouldn't be ripping it out...  Do you have ideas for test cases for the original escape logic?

File: scim-spec/scim-spec-schema/src/main/java/org/apache/directory/scim/spec/filter/AttributeComparisonExpression.java [hunk 1]
```diff
@@ -88,14 +86,7 @@ private String createCompareValueString() {
     if (this.compareValue == null) {
       compareValueString = "null";
     } else if (this.compareValue instanceof String) {
-      // TODO change this to escapeJson() when dependencies get upgraded
-      String escaped = StringEscapeUtils.escapeEcmaScript((String) this.compareValue)
-          // StringEscapeUtils follows the outdated JSON spec requiring "/" to be escaped, this could subtly break things
-          .replaceAll("\\\\/", "/")
-          // We don't want single-quotes escaped, this will be unnecessary with escapeJson()
-          .replaceAll("\\\\'", "'");
```
Comment (joshuapsteele) [inline scim-spec/scim-spec-schema/src/main/java/org/apache/directory/scim/spec/filter/AttributeComparisonExpression.java:96]: Sorry, just now giving this a quick look, @bdemers. Can we note for posterity, even if just in this PR convo, where `escapeJson()` is now being used?

File: scim-spec/scim-spec-schema/src/main/java/org/apache/directory/scim/spec/filter/ExpressionBuildingListener.java [hunk 2]
```diff
@@ -160,14 +154,8 @@ public FilterExpression getFilterExpression() {
...
   private static Object parseJsonType(String jsonValue) {
     if (jsonValue.startsWith("\"")) {
-      String doubleEscaped = jsonValue.substring(1, jsonValue.length() - 1)
-          // StringEscapeUtils follows the outdated JSON spec requiring "/" to be escaped, this could subtly break things
-          .replaceAll("\\\\/", "\\\\\\\\/")
-          // Just in case someone needs a single-quote with a backslash in front of it, this will be unnecessary with escapeJson()
-          .replaceAll("\\\\'", "\\\\\\\\'");
-
-      // TODO change this to escapeJson() when dependencies get upgraded
-      return StringEscapeUtils.unescapeEcmaScript(doubleEscaped);
```
Comment (joshuapsteele) [inline scim-spec/scim-spec-schema/src/main/java/org/apache/directory/scim/spec/filter/ExpressionBuildingListener.java:170]: @bdemers Can we note for posterity, even if just in this PR convo, where `escapeJson()` is now being used?

**Review by joshuapsteele — APPROVED** [review]
Changes look good to me. Would just like to clarify where `escapeJson()` is now being used in the relevant flows here.

File: scim-spec/scim-spec-schema/src/main/java/org/apache/directory/scim/spec/filter/ExpressionBuildingListener.java (hunk 2 above)
Comment (bdemers) [reply scim-spec/scim-spec-schema/src/main/java/org/apache/directory/scim/spec/filter/ExpressionBuildingListener.java:170]: I was hoping @chrisharm would chime in 🤞 
My take is that the escape would happen at a different level:
- filters passed in as a query param would be URL escaped
- Patch paths, would be JSON escaped automatically by Jackson.

Unless I'm missing something i think it would always be problematic to handle escaping outside of the context where it's used.

**Comment by bdemers** [comment]
@joshuapsteele  getting back to this now, sorry about the delay.

I did some poking around related to your question about the where is the escape used now.
It's not used (well, not directly by SCIMple)

The two points where I see that that would need escaping are:

1. A search with a filter in a URL parameter. e.g. `/Users?filter=userName eq \"jcoder\"`
The URL escaping here is left to the JAX-RS framework used which will decode the query parameters
This scenario is covered in: `UsersIT.invalidUserNameFilter()`

2. A patch request, that uses a filter as the `path` e.g. `"path": "members[value eq \"jcoder\"]"
This scenario is covered in `GroupsIT.updateGroupWithPatch`

The longer answer is that the JSON escaping happens by automatically by the parser when serialized.

In the example above if I set `path` to the value of `members[value eq "jcoder"]`, any JSON library would output something like:

```json
{
"path": "members[value eq \"jcoder\"]"
}
```
Where the quotes are automatically escaped.
